### ISSUE TITLE
[Feature Request]: Support for Alternative S3 Storage Providers in Test Reports Slack notifications links

### ISSUE THREAD

**Issue by andrzejmikolajczakds** [st-tech/gatling-operator#122]
### Summary

We would like to request the capability to run tests and obtain reports from various S3 storage providers.

Currently, it is possible to send reports files to other S3 providers by using cloudStorageSpec.provider="aws" and setting the RCLONE_* environment variables. However, the Slack notifications contain a link with the "s3.amazonaws.com" host, which is specific to AWS.

We propose an enhancement to allow the Slack notification links to support others than AWS S3 providers.

I am willing to contribute to this improvement in the gatling-operator.

Thank you for considering this request.

**Comment by kane8n** [comment]
@andrzejmikolajczakds 
I understand that this is a proposal to support S3 compatible storage as described in `https://rclone.org/s3/#configuration`.
I have no particular objection and would appreciate your contribution!

> I am willing to contribute to this improvement in the gatling-operator.

We would greatly appreciate your contribution!
Please submit a Pull Request, and we will review it!

**Comment by andrzejmikolajczakds** [comment]
Hi @kane8n,

I've created a [PR](https://github.com/st-tech/gatling-operator/pull/123). I'm not sure if you're receiving notifications for new PRs in the repository, so I wanted to give you a heads-up.

Thanks!

**Comment by kane8n** [comment]
@andrzejmikolajczakds 
Merge the PullRequest and close this issue.
It has been released in v0.9.9.
Thanks for your contribution!
