### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by yokawasa** [st-tech/gatling-operator#22]
At least, the following docs are needed

- Architecture design doc
- features list
- Quick start guide
- Configuration docs
- API reference

**Comment by yokawasa** [comment]
@tmrekk121 
let me assign Quick start guide update to you.

- [ ] Quick start guide

**Comment by tmrekk121** [comment]
https://github.com/st-tech/gatling-operator/pull/41#pullrequestreview-898513325
