### ISSUE TITLE
Add daily vulnerability scan CI 

### ISSUE THREAD

**Issue by yokawasa** [st-tech/gatling-operator#45]

**Comment by R-HNF** [comment]
I'm going to use [aquasecurity/trivy-action](https://github.com/aquasecurity/trivy-action).

I compared the following three candidates:
1. [Azure/container-scan](https://github.com/Azure/container-scan)
2. [aquasecurity/trivy-action](https://github.com/aquasecurity/trivy-action)
3. [crazy-max/ghaction-container-scan](https://github.com/crazy-max/ghaction-container-scan) 


aquasecurity/trivy-action
* Available on GitHub Marketplace: 1 is not published. 3 is available.
* It supports `timeout` option. The others do not support `timeout`.
* It's recently maintained and has more stars.
* The license is [Apache License Version 2.0](https://github.com/aquasecurity/trivy-action/blob/master/LICENSE)
